# This file is covered by the LICENSE file in the root of this project.
labels: 
  0 : "unlabeled"
  1 : "alive"
  2 : "1h"
  3 : "10h"
  4 : "100h"
  5 : "1000h"

color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  2 : [245, 150, 100]
  3 : [245, 230, 100]
  4 : [250, 80, 100]
  5 : [150, 60, 30]
  
content: # as a ratio with the total number of points
  0: 0.31317276516715514
  1: 0.2379267659773222
  2: 0.3175505301988713
  3: 0.058071223665266236
  4: 0.02524398687922081
  5: 0.04803472811216429

# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0 : 0     # "unlabeled"
  1 : 1     # "outlier" mapped to "unlabeled" --------------------------mapped
  2 : 2     # "car"
  3 : 3     # "bicycle"
  4 : 4     # "bus" mapped to "other-vehicle" --------------------------mapped
  5 : 5     # "motorcycle"
  
learning_map_inv: # inverse of previous map
  0 : 0     # "unlabeled"
  1 : 1     # "outlier" mapped to "unlabeled" --------------------------mapped
  2 : 2     # "car"
  3 : 3     # "bicycle"
  4 : 4     # "bus" mapped to "other-vehicle" --------------------------mapped
  5 : 5     # "motorcycle"

learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "car"
  2: False     # "bicycle"
  3: False     # "motorcycle"
  4: False     # "truck"
  5: False     # "other-vehicle"
  
split: # sequence numbers
  train:
    - 0

  valid:
    - 2

  test:
    - 1
