apiVersion: apps/v1
kind: Deployment
metadata:
  name: cenet-seg
  labels:
    k8s-app: cenet-seg
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cenet-seg
  template:
    metadata: 
      labels:
        k8s-app: cenet-seg
    spec:
      containers:
      - name: cenet-seg-pod
        image: ghcr.io/darthiv02/img-seg-lidar:1.2
        command: ["sleep", "infinity"]
        volumeMounts:
          - mountPath: /root/dataset
            name: tls-data-ivannia
          - mountPath: /root/dataset-4
            name: tls-data-ivannia-4
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: "64G"
            cpu: "1"
          requests:
             memory: "64G"
             cpu: "1"
      volumes:
        - name: tls-data-ivannia
          persistentVolumeClaim:
            claimName: tls-data-ivannia
        - name: tls-data-ivannia-4
          persistentVolumeClaim:
            claimName: tls-data-ivannia-4
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10